### ISSUE TITLE
Grid Display?

### ISSUE THREAD

**Issue by lexterror** [cgwire/js-3d-model-viewer#5]
Are there any options for displaying the grid?

Thank you!

**Comment by frankrousseau** [comment]
Hello @lexterror,

What do you mean by the grid?

**Comment by lexterror** [comment]
By grid I meant the 3D axis with lines. I really like using js-3d-model-viewer. I currently switched to using "Three.js" because it allows textures. I hope you can also support textures at some point!

**Comment by frankrousseau** [comment]
js-3d-model-viewer is a wrapper around Three.js. So everything that is available in Three can be added to this viewer.

**Comment by frankrousseau** [comment]
I added an option to show a grid. It probably needs improvement but it will allow you to give some feedback.
