### ISSUE TITLE
cors error

### ISSUE THREAD

**Issue by hareeshreddy13** [cgwire/js-3d-model-viewer#9]
when i use .obj file from amazon s3 bucket getting cors error

![image](https://user-images.githubusercontent.com/25954694/127502252-8f409f03-deaa-4d0a-b729-4c4a82c786bf.png)

**Comment by frankrousseau** [comment]
Hello, 
Sorry for the late reply. You this error because the files doesn't live on the same server. I will add soon information to set up a development environment. It will allow you to tinker with the demo.
